version: '3.8'

services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
  


